entrevista = {'text': ' É muito difícil prever qual vai ser o impacto da inteligência artificial nos empregos, mas a gente sabe que algumas indústrias vão ser mais impactadas no primeiro momento que outras. Por exemplo, a gente sabe que atendimento de call center, atendimento ao consumidor, isso tem uma chance grande de ser automatizado. Vários serviços de direito, por exemplo, de escritório de vocacia, também podem ser automatizados. Então, a gente deve pensar muito mais em termos de quais tarefas podem ser automatizadas e não empregos completamente. Certamente, a gente vê mais tipos de trabalho que podem ser mais automatizados que outros. O tema de quais empresas podem lucrar mais com a inteligência artificial, eu citaria especialmente a OpenAI, que é a empresa que trouxe esse assunto, a tona via chat.pt e outras funcionalidades. Certamente, a Microsoft que investiu na OpenAI, e acho que foi aqui mais rapidamente incluiu as funcionalidades de inteligência artificial nos seus produtos, no Word, no PowerPoint, no Excel, e o Google está acorrendo um pouco por fora, porque ele atrasou um pouco o uso dessas tecnologias nos seus produtos. Mas eu acho que a grande empresa em que pouca gente fala é a meta, é o Facebook, que tem o investimento muito grande em diversas coisas relacionadas à inteligência artificial, especialmente e até suprinentemente abrindo o código de várias invenções deles. O impacto no Brasil é difícil da gente mensurada, a gente saber. Talvez a inteligência artificial seja uma ferramenta que permita com que a gente crie em pregos um pouco mais produtivos, a gente tem problemas de produtividade frente a outros concorrentes. Então, a IPA pode ser, talvez, o grande equalisador em termos de capacidade produtiva. Mas a gente certamente está muito para trás em termos de patentes, de conhecimento, a gente vai consumir o que vem de fora, mas a gente pode achar formas criativas de utilizar essas tecnologias. Certamente a inteligência artificial impacta a programação, a forma com que a gente aprende a fazer programas de computador. É muito difícil saber se a gente precisa mais ou menos aprender uma linguagem como Python, por exemplo, dado que produtos como chat, chat, e PT, o Copilot, do GitHub, podem te ajudar a programar, a fazer código, a fazer programas. É difícil dizer qual impacto na programação. O que a gente sabe é que pessoas que já têm alguma familiaridade vão produzir muito mais, porque é como se elas tivessem diversos assistentes, funcionários junios na sua equipe. E a produtividade vai aumentar certamente nas profissões que souberem usar melhor a inteligência artificial, especialmente neste modo, na inteligência artificial e generativa, para poder não automatizar, mas simplificar tarefas que são chatas, seja o primeiro rasco de um texto, seja a sumarização de uma reunião, a criação de uma apresentação, e várias coisas que a gente casta tempo, que não são exatamente trabalhos intelectuais, vários funções vão poder se beneficiar disso. Então eu acho que a produtividade pode aumentar em diversas carreiras, desde que a gente use especialmente para isso. A inteligência artificial tem uma grande capacidade de ser uma tecnologia destrativa, de tirar o nosso tempo, tirar o nosso foco. Muita gente diz que o perigo da inteligência artificial, de que ela pode dominar a rassumana, de a gente olha vários filmes que têm essa visão destópica do futuro, e olha um pouco para frente de quando a inteligência artificial geral, foi mais inteligente humano que a gente vai ter vários problemas. Isso é um risco, claro, isso é um risco existencial, eu acho que ele é menor do que muita gente diz, mas acho que a gente tem que pensar nos perigos da IA, mas em um futuro mais próximo, por exemplo, quando a gente pensa em golpes, é muito mais fácil você criar um golpe personalizado hoje em dia, desinformação e esse tipo de coisa. Então eu acho que há riscos de longo prazo, os extensuais, mas eu me preocuparia mais com os perigos que podem acontecer amanhã. Há muito incertez, no momento, então é difícil precisar qual que vai ser o impacto no jornalismo, mas a gente sabe que, olhando para outras profissões que usam bastante ascritas, sumarização de ideias, não há como fingir que não vai ser afetado. Em grande parte, o trabalho do jornalista é transformado dados, informações brutas, entestos em coisas e informação que pode ser útil para a sociedade. Eu acho que o GPD, tecnologias de IA generativa podem ajudar bastante nisso e eu acho que falta um pouco mais de criatividade para gente imaginar os diferentes cenários.',
 'segments': [{'start': 0.0,
   'end': 7.0,
   'text': ' É muito difícil prever qual vai ser o impacto da inteligência artificial nos empregos,'},
  {'start': 7.0,
   'end': 13.0,
   'text': ' mas a gente sabe que algumas indústrias vão ser mais impactadas no primeiro momento que outras.'},
  {'start': 13.0,
   'end': 19.0,
   'text': ' Por exemplo, a gente sabe que atendimento de call center, atendimento ao consumidor,'},
  {'start': 19.0,
   'end': 23.0,
   'text': ' isso tem uma chance grande de ser automatizado.'},
  {'start': 23.0,
   'end': 31.0,
   'text': ' Vários serviços de direito, por exemplo, de escritório de vocacia, também podem ser automatizados.'},
  {'start': 31.0,
   'end': 37.0,
   'text': ' Então, a gente deve pensar muito mais em termos de quais tarefas podem ser automatizadas'},
  {'start': 37.0, 'end': 39.0, 'text': ' e não empregos completamente.'},
  {'start': 39.0,
   'end': 46.0,
   'text': ' Certamente, a gente vê mais tipos de trabalho que podem ser mais automatizados que outros.'},
  {'start': 47.0,
   'end': 54.0,
   'text': ' O tema de quais empresas podem lucrar mais com a inteligência artificial,'},
  {'start': 54.0,
   'end': 62.0,
   'text': ' eu citaria especialmente a OpenAI, que é a empresa que trouxe esse assunto,'},
  {'start': 62.0,
   'end': 66.0,
   'text': ' a tona via chat.pt e outras funcionalidades.'},
  {'start': 67.0,
   'end': 73.0,
   'text': ' Certamente, a Microsoft que investiu na OpenAI, e acho que foi aqui mais rapidamente'},
  {'start': 73.0,
   'end': 79.0,
   'text': ' incluiu as funcionalidades de inteligência artificial nos seus produtos,'},
  {'start': 79.0,
   'end': 87.0,
   'text': ' no Word, no PowerPoint, no Excel, e o Google está acorrendo um pouco por fora,'},
  {'start': 87.0,
   'end': 93.0,
   'text': ' porque ele atrasou um pouco o uso dessas tecnologias nos seus produtos.'},
  {'start': 93.0,
   'end': 98.0,
   'text': ' Mas eu acho que a grande empresa em que pouca gente fala é a meta,'},
  {'start': 98.0,
   'end': 106.0,
   'text': ' é o Facebook, que tem o investimento muito grande em diversas coisas relacionadas à inteligência artificial,'},
  {'start': 106.0,
   'end': 114.0,
   'text': ' especialmente e até suprinentemente abrindo o código de várias invenções deles.'},
  {'start': 117.0,
   'end': 122.0,
   'text': ' O impacto no Brasil é difícil da gente mensurada, a gente saber.'},
  {'start': 123.0,
   'end': 131.0,
   'text': ' Talvez a inteligência artificial seja uma ferramenta que permita com que a gente crie em pregos'},
  {'start': 131.0,
   'end': 136.0,
   'text': ' um pouco mais produtivos, a gente tem problemas de produtividade frente a outros concorrentes.'},
  {'start': 137.0,
   'end': 143.0,
   'text': ' Então, a IPA pode ser, talvez, o grande equalisador em termos de capacidade produtiva.'},
  {'start': 145.0,
   'end': 150.0,
   'text': ' Mas a gente certamente está muito para trás em termos de patentes, de conhecimento,'},
  {'start': 150.0,
   'end': 158.0,
   'text': ' a gente vai consumir o que vem de fora, mas a gente pode achar formas criativas de utilizar essas tecnologias.'},
  {'start': 161.0,
   'end': 170.0,
   'text': ' Certamente a inteligência artificial impacta a programação, a forma com que a gente aprende a fazer programas de computador.'},
  {'start': 170.0,
   'end': 178.0,
   'text': ' É muito difícil saber se a gente precisa mais ou menos aprender uma linguagem como Python, por exemplo,'},
  {'start': 178.0,
   'end': 183.0,
   'text': ' dado que produtos como chat, chat, e PT, o Copilot, do GitHub,'},
  {'start': 183.0,
   'end': 187.0,
   'text': ' podem te ajudar a programar, a fazer código, a fazer programas.'},
  {'start': 188.0,
   'end': 191.0,
   'text': ' É difícil dizer qual impacto na programação.'},
  {'start': 191.0,
   'end': 197.0,
   'text': ' O que a gente sabe é que pessoas que já têm alguma familiaridade vão produzir muito mais,'},
  {'start': 198.0,
   'end': 203.0,
   'text': ' porque é como se elas tivessem diversos assistentes, funcionários junios na sua equipe.'},
  {'start': 203.0,
   'end': 217.0,
   'text': ' E a produtividade vai aumentar certamente nas profissões que souberem usar melhor a inteligência artificial,'},
  {'start': 217.0,
   'end': 223.0,
   'text': ' especialmente neste modo, na inteligência artificial e generativa,'},
  {'start': 223.0,
   'end': 230.0,
   'text': ' para poder não automatizar, mas simplificar tarefas que são chatas,'},
  {'start': 230.0,
   'end': 239.0,
   'text': ' seja o primeiro rasco de um texto, seja a sumarização de uma reunião, a criação de uma apresentação,'},
  {'start': 239.0,
   'end': 243.0,
   'text': ' e várias coisas que a gente casta tempo, que não são exatamente trabalhos intelectuais,'},
  {'start': 243.0,
   'end': 248.0,
   'text': ' vários funções vão poder se beneficiar disso.'},
  {'start': 248.0,
   'end': 252.0,
   'text': ' Então eu acho que a produtividade pode aumentar em diversas carreiras,'},
  {'start': 252.0,
   'end': 256.0,
   'text': ' desde que a gente use especialmente para isso.'},
  {'start': 256.0,
   'end': 262.0,
   'text': ' A inteligência artificial tem uma grande capacidade de ser uma tecnologia destrativa,'},
  {'start': 262.0,
   'end': 264.0,
   'text': ' de tirar o nosso tempo, tirar o nosso foco.'},
  {'start': 269.0,
   'end': 272.0,
   'text': ' Muita gente diz que o perigo da inteligência artificial,'},
  {'start': 272.0,
   'end': 280.0,
   'text': ' de que ela pode dominar a rassumana, de a gente olha vários filmes que têm essa visão destópica do futuro,'},
  {'start': 280.0,
   'end': 286.0,
   'text': ' e olha um pouco para frente de quando a inteligência artificial geral,'},
  {'start': 286.0,
   'end': 291.0,
   'text': ' foi mais inteligente humano que a gente vai ter vários problemas.'},
  {'start': 291.0,
   'end': 296.0,
   'text': ' Isso é um risco, claro, isso é um risco existencial,'},
  {'start': 296.0,
   'end': 298.0,
   'text': ' eu acho que ele é menor do que muita gente diz,'},
  {'start': 298.0,
   'end': 302.0,
   'text': ' mas acho que a gente tem que pensar nos perigos da IA,'},
  {'start': 302.0,
   'end': 305.0,
   'text': ' mas em um futuro mais próximo, por exemplo,'},
  {'start': 305.0, 'end': 309.0, 'text': ' quando a gente pensa em golpes,'},
  {'start': 309.0,
   'end': 314.0,
   'text': ' é muito mais fácil você criar um golpe personalizado hoje em dia,'},
  {'start': 314.0,
   'end': 317.0,
   'text': ' desinformação e esse tipo de coisa.'},
  {'start': 317.0,
   'end': 319.0,
   'text': ' Então eu acho que há riscos de longo prazo,'},
  {'start': 319.0,
   'end': 326.0,
   'text': ' os extensuais, mas eu me preocuparia mais com os perigos que podem acontecer amanhã.'},
  {'start': 328.0,
   'end': 331.0,
   'text': ' Há muito incertez, no momento, então é difícil precisar'},
  {'start': 331.0,
   'end': 334.0,
   'text': ' qual que vai ser o impacto no jornalismo,'},
  {'start': 334.0,
   'end': 340.0,
   'text': ' mas a gente sabe que, olhando para outras profissões que usam'},
  {'start': 340.0,
   'end': 343.0,
   'text': ' bastante ascritas, sumarização de ideias,'},
  {'start': 343.0,
   'end': 348.0,
   'text': ' não há como fingir que não vai ser afetado.'},
  {'start': 348.0,
   'end': 352.0,
   'text': ' Em grande parte, o trabalho do jornalista é transformado'},
  {'start': 352.0, 'end': 355.0, 'text': ' dados, informações brutas,'},
  {'start': 355.0,
   'end': 361.0,
   'text': ' entestos em coisas e informação que pode ser útil para a sociedade.'},
  {'start': 361.0,
   'end': 369.0,
   'text': ' Eu acho que o GPD, tecnologias de IA generativa podem ajudar bastante nisso'},
  {'start': 369.0,
   'end': 374.0,
   'text': ' e eu acho que falta um pouco mais de criatividade para gente imaginar os diferentes cenários.'}]}